### PR TITLE
adjust grid

### PR DESCRIPTION
**Pull request by Marc-pi**

### CODE REVIEW

**Comment by voltan** [comment]
I am not agree whit this change , make all images to small , my customers use bigger images

**Comment by Marc-pi** [comment]
I asked you to display bigger images, you said no ???? Please center the image

**Comment by Marc-pi** [comment]
@voltan, up ! At minimum center the image !

**Comment by Marc-pi** [comment]
@voltan up

**Comment by voltan** [comment]
I am not agree whit this change , you make image position to small and I use event module to some websites , my customers don't like this

**Comment by Marc-pi** [comment]
as said, please center the image, it is awefull like this
i'll close this PR, seems it was merged with my translation fix

**Pull request closed without merging**
